name: Deploy Magnificent Template App to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Output the deployed URL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace API Key placeholder
        run: |
          # Ensure the path to geminiService.ts is correct relative to the repo root
          SERVICE_FILE="./magnificent-app/services/geminiService.ts"
          if [ -f "$SERVICE_FILE" ]; then
            # Using | as sed delimiter because API keys can have /
            sed -i "s|__GEMINI_API_KEY_PLACEHOLDER__|${{ secrets.GEMINI_API_KEY }}|g" "$SERVICE_FILE"
            echo "API Key placeholder replaced in $SERVICE_FILE"
          else
            echo "Error: $SERVICE_FILE not found. API Key not replaced."
            exit 1
          fi
        env:
          # GEMINI_API_KEY defined by GitHub Secrets
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository content after API key replacement
          # GitHub Pages will serve from the root of this artifact
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
